# Bazel BUILD
#
#  Generated by skproto2epoll from mmpaygitgateway/mmpay_comm/service_export_gen/card_voucher/member_card/application/mmpaymktmembercardmgrmedi/proto/mmpaymktmembercardmgrmedi.proto
#
#  Copyright (C) 2009, GZRD,Tencent. All Rights Reserved.
#
#

load("/code_generator/sktools", "protoc")
protoc(
    name = "mmpaymktmembercardmgrmedi_pb_h",
    srcs = [
        "proto/mmpaymktmembercardmgrmedi.proto",
    ],
    outs = [
        "proto/mmpaymktmembercardmgrmedi.pb.cc",
        "proto/mmpaymktmembercardmgrmedi.pb.h",
    ],
)

cc_library(
    name = "mmpaymktmembercardmgrmediclient",
    srcs = [
        "proto/mmpaymktmembercardmgrmedi.pb.cc",
        "summer_client/skproto/sk_mmpaymktmembercardmgrmedicliproto.pb.cpp",
        "summer_client/skproto/sm_mmpaymktmembercardmgrmedicliproto.pb.cpp",
        "summer_client/client/mmpaymktmembercardmgrmediclient.cpp",
    ],
    hdrs = [
        "proto/mmpaymktmembercardmgrmedi.pb.h",
        "summer_client/client/mmpaymktmembercardmgrmediclient.h",
        "summer_client/skproto/sk_mmpaymktmembercardmgrmedicliproto.pb.h",
        "summer_client/skproto/sm_mmpaymktmembercardmgrmedicliproto.pb.h",
        "summer_client/skproto/sm_mmpaymktmembercardmgrmedibaseclient.pb.h",
    ],
    includes = ['proto', 'summer_client/skproto', 'summer_client/client'],
    deps = [
        "//comm2/svrkit:svrkitepoll",
        "//comm2/svrkit:svrkit_pb",
        "//comm2/tlvpickle:skbuiltintype",
        "//platform/summer:summer",
        		'//mmpaygitgateway/mmpay_comm/service_export_gen/card_voucher/member_card/comm/proto:membercard_proto',
		'//mmpaygitgateway/mmpay_comm/service_export_gen/card_voucher/member_card/comm/proto:membercarddef_proto',
		'//mmpaygitgateway/mmpay_comm/service_export_gen/card_voucher/member_card/comm/proto:membercardright_proto',
		'//mmpaygitgateway/mmpay_comm/service_export_gen/card_voucher/member_card/comm/proto:memberservice_proto',
		'//mmpaygitgateway/mmpay_comm/service_export_gen/card_voucher/member_card/application/mmpaymktmemberservicemgrmedi:mmpaymktmemberservicemgrmediclient',

    ],
    copts = [
        '-Wall',
        '-Werror',
        '-std=c++11',
    ],
    linkopts = [
    ],
    visibility = ["//visibility:public"],
)
